### ISSUE TITLE
Make nginx accept raw config

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/boxy-rails#5]
Example- Another server end-point, etc.

**Comment by sahilm** [comment]
* Would you like to be able to override the template with a raw string?
* I think that managing raw strings might become unwieldy. Refactors will be painful. You thoughts?
* Who will verify if the config is valid?

I suggest extending the template with configuration directives as needed for example add support for an array of server endpoints and so on...

**Comment by vipulnsward** [comment]
Yeah, that would do.
So the aim is to have multiple server endpoints, for things running apart from rails on a different port. 
Say- a reverse proxy for some resource.
If an array of config can handle this, then lets do this.

**Comment by sahilm** [comment]
Sounds good. Please share a few example nginx configs covering the use cases you have in mind so that I can get cracking on this.

**Comment by vipulnsward** [comment]
Here's an example of proxy- 

Socket - 
``nginx
upstream websocket {
    server localhost:8800;
}
```
And then in server - 
```nginx
  location ~ ^/somelocation {
	  proxy_http_version 1.1;
	  proxy_set_header Upgrade $http_upgrade;
	  proxy_set_header Connection $connection_upgrade;
	  proxy_pass http://websocket;
  }
```
